# Generated by Django 6.0.3 on 2026-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_options_product_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề nhỏ (h2)')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề chính (h1)')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mô tả (p)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='app/static/app/images/banners/', verbose_name='Hình nền Banner')),
                ('button_text', models.CharField(default='Xem chi tiết', max_length=50, verbose_name='Chữ nút bấm')),
                ('button_link', models.CharField(default='#', max_length=200, verbose_name='Link nút bấm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Quản lý Banner',
                'ordering': ['order', '-id'],
            },
        ),
    ]
