# Generated by Django 6.0.3 on 2026-04-15 14:15

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.banner_upload_path, verbose_name='Hình nền Banner'),
        ),
    ]
