# Generated by Django 6.0.3 on 2026-04-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_shippingaddress_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='app.category', verbose_name='Danh mục'),
        ),
    ]
