# Generated by Django 6.0.3 on 2026-05-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả sản phẩm'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_info',
            field=models.TextField(blank=True, null=True, verbose_name='Thông tin chất liệu'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_info',
            field=models.TextField(blank=True, null=True, verbose_name='Thông tin kích thước'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã SKU'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Đường dẫn (Slug)'),
        ),
    ]
