# Generated by Django 6.0.3 on 2026-05-08 08:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_description_product_material_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Mô tả sản phẩm'),
        ),
    ]
