# Generated by Django 6.0.3 on 2026-05-13 08:36

import app.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Đường dẫn (Slug)')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Mô tả ngắn')),
                ('content', tinymce.models.HTMLField(verbose_name='Nội dung bài viết')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.image_upload_path, verbose_name='Hình ảnh đại diện')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('is_published', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Tin tức',
                'verbose_name_plural': 'Quản lý Tin tức',
                'ordering': ['-date_added'],
            },
        ),
    ]
