# Generated by Django 6.0.3 on 2026-05-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('chuẩn bị hàng', 'Chuẩn bị hàng'), ('đang giao', 'Đang giao'), ('đã giao', 'Đã giao')], default='chuẩn bị hàng', max_length=20, verbose_name='Trạng thái đơn hàng'),
        ),
    ]
