# Generated by Django 6.0.3 on 2026-05-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('chờ xác nhận', 'Chờ xác nhận'), ('chuẩn bị hàng', 'Chuẩn bị hàng'), ('đang giao', 'Đang giao'), ('đã giao', 'Đã giao')], default='chờ xác nhận', max_length=20, verbose_name='Trạng thái đơn hàng'),
        ),
    ]
